###############################################################################
#
#   Config file for this Snakemake pipeline.
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: maciej.bak@unibas.ch
#   CREATED: 22-11-2019
#   LICENSE: GPL v3.0
#
###############################################################################
---

# genomic annotation in GTF format
gtf: "../../RESOURCES/Homo_sapiens.GRCh38.87.gtf"

# quantified transcripts expression
transcript_quantification: "sample_input.tsv"

# path for the output directory
result_dir: "output_dir"

# sample names (as in the input table)
CONTROL:
  - "WT1"
  - "WT2"
EXPERIMENT:
  - "KD1"
  - "KD2"

# SUPPA parameters:
threshold: "10"
total_filter: "1"
lower_bound: "0.00"

...